// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Md5 = require("md5");

var input = "yzbqklnj";

function run(input, _i) {
  while(true) {
    var i = _i;
    var s = input.concat(i.toString());
    var hash = Md5(s);
    if (hash.startsWith("00000")) {
      return [
              true,
              i
            ];
    }
    _i = i + 1 | 0;
    continue ;
  };
}

function main(param) {
  var result = run(input, 1);
  console.log(result);
  
}

main(undefined);

exports.input = input;
exports.run = run;
exports.main = main;
/*  Not a pure module */
